function initializeFigure()
    global datafig 
    global time_lbl 
    global time
    global position_plot
    global time_val
    
    datafig.Name = 'Acquisition GUI';
    time_lbl = uilabel(datafig, ...
                       'Text', 'Time: ',...
                       'FontSize', 14, ...
                       'FontWeight', 'bold',...
                       'WordWrap', 'off',...
                       'Position', [20 300 100 100]); 
                   
    time_val = uilabel(datafig, ...
                       'Text', string(seconds(time)),...
                       'FontSize', 14,...
                       'WordWrap','off',...
                       'Position', [20 280 100 100]);
              
    
    position_plot = uiaxes(datafig, ...
                           'Position', [150 30 350 350],...
                           'XLim', [0 5],...
                           'YLim', [0 5]); 
    position_plot.XLabel.String = 'X-Position'; 
    position_plot.YLabel.String = 'Y-Position';

    set(time_val, 'String', string(time))
    drawnow

end


% s = seconds(100);
% s.Format = 'hh:mm:ss'
% string(s)